name: hetmech-backend
channels:
  - conda-forge
dependencies:
  - conda-forge::django-extensions=2.1.3
  - conda-forge::django=2.1.3
  - conda-forge::ipykernel=5.1.0
  - conda-forge::pandas=0.23.4
  - conda-forge::psycopg2=2.7.5
  - conda-forge::pydotplus=2.0.2
  - conda-forge::python=3.7.0
  - conda-forge::requests=2.20.0
  - pip:
    - git+https://github.com/hetio/hetio@ae2d0bce46e7137ae8812e99ce0e8301f8b7fa53
    - git+https://github.com/greenelab/hetmech@dc1c14b60b1cb19f87d7ff6d1679e0dae72adc8d
    - neo4j-driver==1.7.0
