name: hetmech-backend
channels:
  - conda-forge
dependencies:
  - conda-forge::django-extensions=2.1.4
  - conda-forge::django=2.1.5
  - conda-forge::graphviz=2.38.0
  - conda-forge::ipykernel=5.1.0
  - conda-forge::pandas=0.24.0
  - conda-forge::psycopg2=2.7.7
  - conda-forge::pydot=1.4.0
  - conda-forge::python=3.7.1
  - conda-forge::pyyaml=3.13
  - conda-forge::requests=2.21.0
  - conda-forge::scipy=1.2.0
  - pip:
    - git+https://github.com/hetio/hetio@7c179b75a5520b3520cc44017325b64c2b655ce2
    - git+https://github.com/hetio/hetmatpy@fe68dabdfea9d83eee0274c19e8d2f9929df228c
    - neo4j-driver==1.7.0
