name: hetmech-backend
channels:
  - conda-forge
dependencies:
  - django-cors-headers=2.5.0
  - django-extensions=2.1.6
  - django-filter=2.1.0
  - django=2.2.1
  - djangorestframework=3.9.3
  - graphviz=2.40.1
  - gunicorn=19.9.0
  - ipykernel=5.1.0
  - neo4j-python-driver=1.7.2
  - numpy=1.16.3
  - pandas=0.24.2
  - pip=19.1
  - psycopg2=2.8.2
  - pydot=1.4.1
  - python=3.7.3
  - pyyaml=5.1
  - requests=2.21.0
  - scipy=1.2.1
  - sqlparse=0.3.0
  - pip:
    - git+https://github.com/hetio/hetio@84f166510bc10c3560430011ff3e6d0b731d878b
    - git+https://github.com/hetio/hetmatpy@80222bc83098b0437cd5520fb11ab8cd184ce216
    - markdown==3.1
